# Generated by Django 3.0.7 on 2022-10-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_number', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('url', models.CharField(max_length=50)),
            ],
        ),
    ]
