# Generated by Django 3.0.7 on 2022-10-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id_number',
        ),
        migrations.AddField(
            model_name='video',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
